namespace: community
name: vmware
version: 0.2.0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags:
  - cloud
  - vmware
  - virtualization
dependencies: {}
repository: git@github.com:ansible-collections/vmware.git
documentation: https://github.com/ansible-collections/vmware/tree/master/docs
homepage: https://github.com/ansible-collections/vmware
issues: https://github.com/ansible-collections/vmware/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
